
(eval-when (:execute :load-toplevel :compile-toplevel)
  #-:asdf (load "/usr/share/common-lisp/source/cl-asdf/asdf.lisp")
  #-:cl-annot (require "cl-annot")
  #-:cl-fad (require "cl-fad")
  #-:cl-fad (require "cl-clasp")
  #-:uffi (require "uffi")
  #-:ironclad (require "ironclad")
  )
(annot:enable-annot-syntax)
